[package]
name = "realworld"
description = "Implementation of the RealWorld API specification in the Rust programming language"
version = "0.1.0"
edition = "2021"
rust-version = "1.71"
repository = "https://github.com/dustin10/realworld-rust"
readme = "./README.md"

[dependencies]
anyhow = "1.0.75"
aws-config = "0.56.1"
aws-sdk-dynamodb = "0.32.0"
axum = { version = "0.6.20", features = ["headers"] }
config = "0.13.3"
dotenvy = "0.15.7"
futures = "0.3.28"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = ["runtime-tokio-native-tls", "postgres", "macros", "uuid"] }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["full"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }

[dev-dependencies]
mockall = "0.11.4"
