version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${RW_DATABASE_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
