signing_key = "default-signing-key"

[http]
port = "7100"

[database]
user = "postgres"
password = ""
url = "localhost:5432"
name = "postgres"
max_connections = "50"
connection_timeout = "60"

[kafka]
servers = "localhost:29092"

[outbox]
channel_size = 128
interval = 30000
batch_size = 100
