pub mod consume;
pub mod produce;

/// Enumerates the errors generated by the event module.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// Occurs when there is an error bootstrapping the Kafka producer or consumer.
    #[error("error initializing Kafka")]
    Initialization {
        #[from]
        source: rdkafka::error::KafkaError,
    },
    /// Occurs when there is an error in the main loop of the outbox processing task.
    #[error("error processing outbox entries")]
    OutboxProcessing {
        #[from]
        source: tokio::task::JoinError,
    },
    /// Occurs when there is an error querying the database for outbox entries.
    #[error("error querying the database for outbox entries")]
    OutboxDatabase {
        #[from]
        source: sqlx::Error,
    },
    /// Occurs when there is an error publishing an event to Kafka.
    #[error("error publishing Kafka event for an outbox entry")]
    OutboxPublish,
    /// Occurs when there is an error consuming events from Kafka.
    #[error("error consuming Kafka events")]
    EventProcessing,
}
