pub mod consume;
pub mod produce;

/// Enumerates the errors generated by the event module.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// Occurs when there is an error during an interaction with the Kafka client library.
    #[error("error during Kafka interaction")]
    Kafka {
        #[from]
        source: rdkafka::error::KafkaError,
    },
    /// Occurs when there is an error in the main loop of the outbox processing task.
    #[error("error processing outbox entries")]
    OutboxProcessing {
        #[from]
        source: tokio::task::JoinError,
    },
    /// Occurs when there is an error querying the database for outbox entries.
    #[error("error querying the database for outbox entries")]
    OutboxDatabase {
        #[from]
        source: sqlx::Error,
    },
}
